name: Video Combiner

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install moviepy

    - name: Ensure output directory exists
      run: mkdir -p output

    - name: Run video combiner script
      run: python main.py

    - name: Commit combined video
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add output/combined_video.mp4
        git commit -m "Add combined video"
        git push
